// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exsttswatphnjxbtilyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4c3R0c3dhdHBobmp4YnRpbHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjgwOTAsImV4cCI6MjA3Mzk0NDA5MH0.JtqPOWPYWepTohC4GtsFB4hE3j7zyY8u9CI6JAxOO3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});